Title: Error in check plugins breaks automation for package info
Component: core
State: open
Date: 2016-07-19 11:56:45
Targetversion: future
Class: nastiness

I did: 

1. Installed an MKP via WATO
2. Dissolved the files
3. Manually began to delete one after the other

As soon as I've deleted some foo.include - the automation for the package
information would stop working sind load_checks() in check_mk.py unconditionally
exists (sys.exit(5)) when a check plugin cannot be loaded.

Better output just a warning and suppress this warning when in 
automation mode.
